name: Build Windows binaries

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  msys:
    runs-on: windows-2019
    strategy:
      matrix:
        mingw: ["MINGW32", "MINGW64"]
        include:
          - mingw: "MINGW32"
            package: "mingw-w64-i686"
          - mingw: "MINGW64"
            package: "mingw-w64-x86_64"
    defaults:
      run:
        shell: bash.exe --login -eo pipefail "{0}"
    env:
      MSYSTEM: ${{ matrix.mingw }}
      CHERE_INVOKING: 1
    name: MSYS2 ${{ matrix.mingw }}
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Saroo savetool
        uses: actions/checkout@v4
        with:
          repository: bucanero/SAROO
          path: saroo

      - name: Set up shell
        run: echo "C:\msys64\usr\bin\" >> $GITHUB_PATH
        shell: pwsh

      - name: Install MinGW requirements
        run: |
          echo "$GITHUB_WORKSPACE"
          #pacman -S --noconfirm ${{ matrix.package }}-zlib-devel
          # build the project

      - name: Build binaries
        run: |
          make
          cd saroo/tools/savetool/
          make
          mv sst ../../../

      - name: Get short SHA
        run: echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
    
      - name: Compress output
        run: |
          tar -zcvf build.tar.gz ss-converter.exe sgm-unpacker.exe sst.exe

      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ env.sha_name }}-${{matrix.mingw}}
          path: build.tar.gz
